// auto-generated by configen
// to add or remove properties, edit the mapping file: 'ConfigApp/EnvironmentConfig/EnvironmentConfig.map'.
// README: https://github.com/theappbusiness/ConfigGenerator/blob/master/README.md

import Foundation

class EnvironmentConfig {

  static let entryPointURL: URL = URL(string: "http://example.com/production")!

  static let enableFileSharing: Bool = true

  static let analyticsKey: String = "haf6d9fha8v56abs"

  static let environment: Environment = .Production

  static let adUnitPrefix: String = "production_ad_unit"

  static let retryCount: Int = 1

}

